### ISSUE TITLE
安装完这个问题

### ISSUE THREAD

**Issue by luyunfeng** [178146582/Fantasy-field#1]
Warning: session_set_cookie_params(): Cannot change session cookie parameters when session is active in /www/wwwroot/image.luyunfeng.cn/framework/core/Framework.php on line 33

**Comment by Aruelius** [comment]
更换PHP版本

**Comment by luyunfeng** [comment]
7.2版本也是不行的吗

**Comment by Aruelius** [comment]
7.1以下ok的，最好是5.6.30
